# Generated by Django 3.2.11 on 2022-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_hobby_factor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='age_factor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minAge', models.IntegerField()),
                ('maxAge', models.IntegerField()),
                ('factor', models.CharField(max_length=30)),
            ],
        ),
    ]
