# Generated by Django 3.2.11 on 2022-02-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0004_age_factor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
            ],
        ),
    ]
