# Generated by Django 3.2.11 on 2022-02-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0005_season'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='season',
            new_name='season_tb',
        ),
    ]
