# Generated by Django 3.2.11 on 2022-02-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0006_rename_season_season_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='season_factor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(max_length=20)),
                ('seasonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.season_tb')),
            ],
        ),
    ]
