# Generated by Django 3.2.11 on 2022-02-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0005_user_hobby_tb'),
        ('site_admin', '0007_season_factor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='season_country_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.country_tb')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.season_factor_tb')),
                ('seasonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.season_tb')),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.state_tb')),
            ],
        ),
    ]
