# Generated by Django 3.2.11 on 2022-02-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.country_tb')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.state_tb')),
            ],
        ),
    ]
