# Generated by Django 3.2.11 on 2022-02-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0002_register_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_tb',
            old_name='country',
            new_name='countryid',
        ),
        migrations.RenameField(
            model_name='register_tb',
            old_name='state',
            new_name='stateid',
        ),
    ]
