# Generated by Django 3.2.11 on 2022-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0003_auto_20220221_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='security_answer',
            field=models.CharField(default='no data', max_length=30),
        ),
        migrations.AddField(
            model_name='register_tb',
            name='security_question',
            field=models.CharField(default='no data', max_length=50),
        ),
    ]
