# Generated by Django 3.2.11 on 2022-02-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_hobby_tb'),
        ('site_user', '0004_auto_20220221_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_hobby_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.hobby_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.register_tb')),
            ],
        ),
    ]
