# Generated by Django 3.2.11 on 2022-02-25 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0006_message_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('messageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.message_tb')),
                ('receiverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.register_tb')),
            ],
        ),
    ]
