# Generated by Django 3.2.11 on 2022-02-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0008_contact_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('blackedid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackedid', to='site_user.register_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='site_user.register_tb')),
            ],
        ),
    ]
