# Generated by Django 3.2.11 on 2022-02-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0008_season_country_tb'),
        ('site_user', '0009_blacklist_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_hobby_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.hobby_factor_tb')),
                ('hobbyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.user_hobby_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_user.register_tb')),
            ],
        ),
    ]
