# Generated by Django 3.2.11 on 2022-03-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_user', '0013_register_tb_filter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_tb',
            name='filter_status',
        ),
        migrations.AddField(
            model_name='message_tb',
            name='filter_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
